-- 0026: Add the "Taken" season and make it the active series.
-- Reef of Thrones moves to draft so Taken is the one on the /story page.

UPDATE story_series SET status = 'draft', updated_at = datetime('now') WHERE slug = 'reef-of-thrones';

INSERT OR IGNORE INTO story_series (id, slug, title, total_scenes, start_date, status)
VALUES (2, 'taken', 'Taken', 24, date('now'), 'active');

INSERT OR IGNORE INTO story_scenes (series_id, scene_order, release_offset_days, title, setting, script) VALUES
 (2, 1, 0, 'The Bored Tank', 'The Tank', '{"prop": "The fish are bored. Again.", "narration": "Another slow day in the tank. The cast is restless and itching for a story.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "content", "line": "Stay where I can see you, kid. The world out there has teeth."}, {"speaker": "seahorse", "name": "Coral", "position": "right", "expression": "happy", "line": "Dad, I am not a baby anymore. I want to SEE things."}]}'),
 (2, 2, 1, 'A Plan Hatches', 'The Tank', '{"prop": "A tiny suitcase has appeared by the castle.", "narration": "Bianca arrives with big ideas.", "beats": [{"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "happy", "line": "Coral! Come abroad with me. The big city. Lights. Adventure."}, {"speaker": "seahorse", "name": "Coral", "position": "center", "expression": "happy", "line": "Yes. A thousand times yes. I just have to ask my dad."}]}'),
 (2, 3, 2, 'One Rule', 'The Tank', '{"prop": "The toy phone glints in the gravel.", "narration": "Pinch agrees, but he has a condition.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "hungry", "line": "Fine. But you call me the second you land. Every time. No exceptions."}, {"speaker": "seahorse", "name": "Coral", "position": "right", "expression": "happy", "line": "I promise, Dad. I love you."}]}'),
 (2, 4, 3, 'In Transit', 'In Transit', '{"prop": "A toy airplane drifts across the tank.", "narration": "The journey begins.", "beats": [{"speaker": "seahorse", "name": "Coral", "position": "center", "expression": "happy", "line": "We are really doing this, Bianca!"}, {"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "happy", "line": "Told you. Best trip of our lives."}]}'),
 (2, 5, 4, 'The Bright City', 'The Bright City', '{"prop": "A tiny Eiffel Tower now stands in the tank. Nobody knows why.", "narration": "They arrive somewhere dazzling.", "beats": [{"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "happy", "line": "Look at this place! I could stay forever."}, {"speaker": "seahorse", "name": "Coral", "position": "left", "expression": "content", "line": "Let me call my dad first, like I promised."}]}'),
 (2, 6, 5, 'Watched', 'The Bright City', '{"prop": "The light dims at the edge of the reef.", "narration": "Something is watching them.", "beats": [{"speaker": "stranger", "name": "A Stranger", "position": "right", "expression": "hungry", "line": "Two travelers. Alone. Perfect."}, {"speaker": "seahorse", "name": "Coral", "position": "left", "expression": "peckish", "line": "Bianca... I think that fish is following us."}]}'),
 (2, 7, 6, 'Bad Feeling', 'The Apartment', '{"prop": "A cracked porthole prop appears.", "narration": "Bianca waves off the worry.", "beats": [{"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "happy", "line": "You worry too much. Help me unpack."}, {"speaker": "seahorse", "name": "Coral", "position": "left", "expression": "peckish", "line": "I have a really bad feeling about this."}]}'),
 (2, 8, 8, 'The Taking', 'The Apartment', '{"prop": "Shadows pour in from every crack.", "narration": "The gang strikes.", "beats": [{"speaker": "stranger", "name": "The Gang", "position": "center", "expression": "hungry", "line": "Grab the bright one first."}, {"speaker": "angelfish", "name": "Bianca", "position": "left", "expression": "very_hungry", "line": "Coral! Hide! Call your dad, NOW!"}]}'),
 (2, 9, 10, 'The Call', 'The Apartment', '{"prop": "The phone, ringing in the dark.", "narration": "Coral hides and dials.", "beats": [{"speaker": "seahorse", "name": "Coral", "position": "left", "expression": "very_hungry", "line": "Dad! They took Bianca! I can hear them coming!"}, {"speaker": "crab", "name": "Mr. Pinch", "position": "right", "expression": "hungry", "line": "Listen to me. Stay calm. Tell me everything you see."}]}'),
 (2, 10, 12, 'A Specific Set of Skills', 'The Apartment', '{"prop": "A single beam of light falls on the phone.", "narration": "Pinch speaks to whoever is listening.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "hungry", "line": "I do not know who you are. But I have a very specific set of skills."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "very_hungry", "line": "Skills that make me a nightmare for fish like you. Let her go."}]}'),
 (2, 11, 14, 'Too Late', 'The Apartment', '{"prop": "A swirl of bubbles where she stood.", "narration": "The line goes quiet.", "beats": [{"speaker": "stranger", "name": "The Gang", "position": "right", "expression": "hungry", "line": "Good luck, old crab. You will never find us."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "very_hungry", "line": "I will find you. And I will get her back."}]}'),
 (2, 12, 16, 'The Hunt Begins', 'The Tank', '{"prop": "The water goes cold and grey.", "narration": "Pinch is alone, and resolved.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "center", "expression": "sad", "line": "Hold on, kid. I am coming for you."}]}'),
 (2, 13, 18, 'Crossing Over', 'In Transit', '{"prop": "The toy plane again, pointed the other way.", "narration": "Pinch travels to the city.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "center", "expression": "hungry", "line": "Every single hour matters now. Move."}]}'),
 (2, 14, 20, 'An Old Friend', 'Otto''s Hideout', '{"prop": "A tattered map unrolls across the gravel.", "narration": "Pinch finds his old contact.", "beats": [{"speaker": "pufferfish", "name": "Otto", "position": "right", "expression": "content", "line": "Pinch! I heard. Whatever you need, it is yours."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "hungry", "line": "I need names. Who runs the trade in this city?"}]}'),
 (2, 15, 22, 'Reading the Tide', 'Otto''s Hideout', '{"prop": "A glowing clue shimmers in the sand.", "narration": "Stella studies the trail.", "beats": [{"speaker": "starfish", "name": "Stella", "position": "center", "expression": "content", "line": "The current carried them east. Follow the cold water."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "content", "line": "Then east I go."}]}'),
 (2, 16, 24, 'Into the Den', 'The Den', '{"prop": "Stacked crates loom in the murky water.", "narration": "Pinch slips inside the gang''s den.", "beats": [{"speaker": "stranger", "name": "The Gang", "position": "right", "expression": "hungry", "line": "You are not supposed to be back here."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "content", "line": "Wrong. I am exactly where I am supposed to be."}]}'),
 (2, 17, 26, 'A Name', 'The Den', '{"prop": "A sudden cloud of sand erupts.", "narration": "He gets what he came for.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "very_hungry", "line": "The buyer. Give me a name, and you swim away."}, {"speaker": "stranger", "name": "The Gang", "position": "right", "expression": "sad", "line": "...The Clam. They sold her to the Clam."}]}'),
 (2, 18, 28, 'The Chase', 'The Chase', '{"prop": "Motion streaks blur the whole reef.", "narration": "A chase through the rocks.", "beats": [{"speaker": "crab", "name": "Mr. Pinch", "position": "center", "expression": "hungry", "line": "Nobody outruns a crab on his own reef."}]}'),
 (2, 19, 30, 'Empty Crate', 'The Empty Room', '{"prop": "An open, empty crate sits in the gloom.", "narration": "He finds Bianca, but not Coral.", "beats": [{"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "sad", "line": "Pinch? You came... but they already took Coral to him."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "hungry", "line": "Then I am not finished. Where?"}]}'),
 (2, 20, 32, 'The Trail Ends', 'The Kingpin''s Hall', '{"prop": "An ornate throne-shell rises from the dark.", "narration": "The trail leads to the buyer.", "beats": [{"speaker": "starfish", "name": "Stella", "position": "left", "expression": "content", "line": "Beyond that arch. He never leaves his throne."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "right", "expression": "very_hungry", "line": "Good. Then he will be easy to find."}]}'),
 (2, 21, 34, 'The Kingpin', 'The Kingpin''s Hall', '{"prop": "The Clam sits, vast and silent.", "narration": "The confrontation.", "beats": [{"speaker": "clam", "name": "The Clam", "position": "center", "expression": "sad", "line": "You are brave, crab. Brave, and very far from home."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "very_hungry", "line": "Give me my daughter. This is your only warning."}]}'),
 (2, 22, 36, 'The Rescue', 'The Kingpin''s Hall', '{"prop": "The whole tank shudders.", "narration": "Pinch makes his move.", "beats": [{"speaker": "seahorse", "name": "Coral", "position": "right", "expression": "very_hungry", "line": "DAD!"}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "hungry", "line": "I have got you. Close your eyes. We are leaving."}]}'),
 (2, 23, 38, 'Reunited', 'The Tank', '{"prop": "Warm light floods back into the reef.", "narration": "Father and daughter, together again.", "beats": [{"speaker": "seahorse", "name": "Coral", "position": "right", "expression": "happy", "line": "You found me. You actually found me."}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "content", "line": "I will always find you. Always."}]}'),
 (2, 24, 40, 'Curtain Call', 'The Tank', '{"prop": "The props fade away, one by one.", "narration": "The play is over. The tank is just a tank again.", "beats": [{"speaker": "angelfish", "name": "Bianca", "position": "right", "expression": "happy", "line": "That was incredible. What do we perform next?"}, {"speaker": "crab", "name": "Mr. Pinch", "position": "left", "expression": "content", "line": "Give me five minutes of peace. Five."}, {"speaker": "starfish", "name": "Stella", "position": "center", "expression": "happy", "line": "The audience is already bored. Places, everyone."}]}');
